### ISSUE TITLE
Profile Pic not showing after upload

### ISSUE THREAD

**Issue by poseso** [rappasoft/laravel-5-boilerplate#1014]
BP 5.5

When I upload an avatar it successfully get stored under storage/app/public/avatars/ but when I do {{ $logged_in_user->picture }}    its looking in http://sgc.local/avatars/SB0Q3V8BpbnPrXU7MH3DNbn2lCF2vTNfqjyQ1lRs.jpeg  <- and the file doesn't load, is there something I need to look at? or something has change? 

plain {{ $logged_in_user->picture }} displays avatars/jbsFdRIZXriJq1hAzoJeJ1qrMigZCtbzyXelvYOG.jpeg

Thx

**Comment by bambamboole** [comment]
@poseso you are right. There is a missing `'storage/'` in the `getPicture` method of the `UserMethod Trait` . That should fix it:
`return url('storage/'.$this->avatar_location);`

If you have the time to make a PR, this is a very good First Time Contribution.

**Comment by poseso** [comment]
oh didn't noticed it's actually missing, that solved the issue, I'll close this issue now, I think @rappasoft can add that little fix without the need of a PR for such small fix, but I can PR if you want

**Comment by rappasoft** [comment]
I will definitely forget lol

**Comment by poseso** [comment]
haha i'll make the PR

**Comment by geekz-reno** [comment]
@all, i still cannot view my avatar after upload, same with @poseso and check on usermethod like @bambamboole  say it already have storage path, but avatar still not show,

**Comment by geekz-reno** [comment]
> @ALL, i still cannot view my avatar after upload, same with @poseso and check on usermethod like @bambamboole say it already have storage path, but avatar still not show,
> 
> my image url /storage/avatars/aw5xStMhHMs98SkQShRxxEUB5hjCiLhsOGncIMNR.png
> after upload my image are stored in /storage/app/public/avatars

sorry, my bad, i forgot to hit `php artisan storage:link`
